import process from "node:process";
import esbuild from "esbuild";
import info from "./package.json" assert { type: "json" };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/index.ts"],
  bundle: true,
  external: ["commitlint"],
  format: "esm",
  platform: "node",
  target: "node2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: `bin/${info.name}.js`,
  packages: "external", // This will make esbuild treat all packages in node_modules as external
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
