# Example commitlint configuration for monorepo with namespace support
# Save as: commitlint.config.yaml

extends:
  - '@commitlint/config-conventional'

rules:
  # Namespace configuration for monorepo
  namespace-enum: [2, 'always', ['apps/*', 'libs/*', 'tools/*']]
  namespace-empty: [2, 'never']
  
  # Standard conventional commit rules
  type-enum:
    - 2
    - always
    - [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test'
      ]
  
  # Subject and scope rules
  subject-case: [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']]
  subject-empty: [2, 'never']
  subject-full-stop: [2, 'never', '.']
  subject-max-length: [2, 'always', 100]
  
  # Optional scope rules
  scope-case: [2, 'always', 'lower-case']
  scope-empty: [0, 'never']